version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: capstone-dev-db
    environment:
      POSTGRES_DB: test33
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5430:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-dev.sql:/docker-entrypoint-initdb.d/init-dev.sql

volumes:
  postgres-data:
