openapi: 3.0.3
info:
  title: PocketGrow API Documentation
  description: |-
    PocketGrow REST API Documentation
  # contact:
  #   email: pocketgrow@email.com
  version: 1.0.1
externalDocs:
  description: Github Repo
  url: https://github.com/mune-kyun/PocketGrow-BE
servers:
  - url: localhost
tags:
  - name: Auth
    description: Operations about auth
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Create user
      description: ""
      operationId: createUser
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Users'
          application/xml:
            schema:
              $ref: '#/components/schemas/Users'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Users'
      responses:
        default:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
            application/xml:
              schema:
                $ref: '#/components/schemas/Users'
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login User
      description: ''
      operationId: loginUser
      parameters:
        - name: email
          in: query
          description: email for login
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: The password for login in clear text
          required: true
          schema:
            type: string
      responses:
        '200':
          description: login succesfully
          content:
            application/xml:
              schema:
                type: string
            application/json:
              schema:
                type: string
        '400':
          description: Invalid username/password      
components:
  schemas:
    Users:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        email:
          type: string
          example: john@email.com
        password:
          type: string
          example: '12345'
        fullname:
          type: string
          example: John James
        dateOfBirth:
          type: string
          format: date
          example: "2002-01-01"
      xml:
        name: user
  requestBodies:
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Users'